EXTRAFLAGS += -flto
LTO_ENABLE = yes
LINK_TIME_OPTIMIZATION_ENABLE = yes
ENCODER_MAP_ENABLE = yes
OLED_ENABLE = yes
SPLIT_KEYBOARD = yes
WPM_ENABLE = yes

MOUSEKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
MIDI_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
RGBLIGHT_ENABLE = no
